name: Trigger Sync API

on:
  schedule:
    # Run every 30 minutes
    - cron: "*/30 * * * *"
  # Optional: Allow manual triggering
  workflow_dispatch:

jobs:
  trigger-sync:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Trigger sync endpoint
        run: |
          response=$(curl -s -w "\n%{http_code}" https://dharmaradio.pages.dev/api/sync)
          status_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | sed '$d')

          echo "Response body: $body"
          echo "Status code: $status_code"

          if [ "$status_code" != "200" ]; then
            echo "Error: Sync endpoint returned status code $status_code"
            exit 1
          fi
